project:
  output-dir: ../build/docs/
  type: website
  render:
    - index.qmd

website:
  repo-url: https://github.com/blw-ofag-ufag/semantic-web-project-template
  repo-actions: [source,issue]

bibliography: references.bib

format:
  html:
    toc: true
    number-sections: true
  gfm: 
    toc: true
    number-sections: true
  docx:
    toc: true
    reference-doc: https://s.zazuko.com/MHXTkQ
    link-citations: true
  typst: default