project:
  output-dir: ../build/docs/
  type: website
  render:
    - de/index.qmd
    - fr/index.qmd
    - en/index.qmd

website:
  title: eCH-1234 Version 2.4.1 (Working Draft)
  repo-url: https://github.com/blw-ofag-ufag/semantic-web-template
  repo-subdir: docs
  repo-actions: [source, issue]
  favicon: assets/favicon.svg
  navbar:
    background: dark
    right:
      - icon: github
        href: https://github.com/blw-ofag-ufag/semantic-web-template
      - icon: envelope
        href: mailto:agridata.ch@blw.admin.ch
      - icon: translate
        menu:
          - text: English
            href: /en/index.html
          - text: Deutsch
            href: /de/index.html
          - text: Français
            href: /fr/index.html
  announcement:
    icon: info-circle
    dismissable: true
    content: Diese Seite beinhaltet einen *Working Draft* und kann sich dadurch laufend verändern. Für eine aktuelle Version, besuchen Sie [ech.ch](https://ech.ch/).
    type: warning

bibliography: references.bib

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 2
    number-sections: true
    syntax-definitions:
     - assets/sparql.xml
     - assets/turtle.xml
  gfm: 
    toc: true
    toc-depth: 2
    number-sections: true
  docx:
    toc: true
    toc-depth: 2
    number-sections: true
    reference-doc: https://s.zazuko.com/MHXTkQ
    link-citations: true
  typst:
    toc: true
    toc-depth: 2
    number-sections: true
    mainfont: Nimbus Sans
    fontsize: 12pt
    include-in-header: assets/typst-header.typ
    include-before-body: assets/typst-before-body.typ
    syntax-definitions:
     - assets/sparql.xml
     - assets/turtle.xml