name: Build and Test Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Needed to allow the Action to post check runs and annotations
permissions:
  contents: read
  checks: write
  pull-requests: read

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Setup Java (Required for ROBOT)
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Setup Build Dependencies
        run: make setup

      - name: Run Full Pipeline and Pytest
        run: make test
        env:
          FORCE_COLOR: 1

      - name: Publish Clean Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure() # Ensures the test results are published even if pytest fails
        with:
          report_paths: 'build/test-results.xml'
          check_name: 'Pytest Results'