name: Build and Test Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Needed to allow the Action to post test result annotations/comments to the PR
permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Setup Java (Required for ROBOT)
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Setup Build Dependencies
        run: make setup

      - name: Run Full Pipeline and Pytest
        run: make test
        env:
          FORCE_COLOR: 1

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always() # Ensures the test results are published even if pytest fails
        with:
          files: "build/test-results.xml"